/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rti_Windows;
import java.awt.Dimension;
import java.awt.Point;
import java.util.StringTokenizer;
import java.util.Vector;

/**
 *
 * @author tiboo
 */
public class Buy_ticket_window extends javax.swing.JFrame {
    
    private CustomerWindow Mywindow;

    private int nbpassager =0;
    private boolean newpassager=false;
    private boolean newtitu = false;
    
    private String myliste;
    public Vector<String> listeclientstitu;
    public Vector<String> listeclientsacc;
    public Vector<String> listetraversees;
    
    public Vector<javax.swing.JTextField> tabJTFnom;
    public Vector<javax.swing.JTextField> tabJTFprenom;
    public Vector<javax.swing.JTextField> tabJTFadresse;
    public Vector<javax.swing.JTextField> tabJTFpays;
    public javax.swing.JTextField JTFemailtitu;
    public javax.swing.JTextField JTFadressetitu;
    public javax.swing.JTextField JTFpaystitu;
    public javax.swing.JTextField JTFnomtitu;
    public javax.swing.JTextField JTFprenomtitu;
    
    public javax.swing.JLabel labemail,labadresse,labpays;
    public Vector<javax.swing.JLabel> labnpassager;
    
    public Vector<javax.swing.JCheckBox> chknpassager;
    
    public Vector<javax.swing.JComboBox<String>> CMPassager;
    
    private javax.swing.GroupLayout layout;
    /**
     * Creates new form Buy_ticket_window
     */
    public Buy_ticket_window(CustomerWindow mywindow, String liste) {
        initComponents();
          myliste=liste;
        Mywindow = mywindow;
        listeclientstitu = new Vector<String>();
        listeclientsacc = new Vector<String>();
        listetraversees = new Vector<String>();
        boolean nouvClient = false; 
       
        StringTokenizer strtok = new StringTokenizer(myliste,"#");
     
        boolean end=false;
        while(end==false)
        {
            String temp = strtok.nextToken();
            if(temp.equals("end")==false)
            {
                temp=("Traversée num " +temp+ " depuis "+strtok.nextToken() + " à " + strtok.nextToken()+ " le " +strtok.nextToken()+ " ");
                listetraversees.add(temp);
            }
            else
            {
                end=true;
            }
        }
        end=false;
        while(end==false)
        {
            String temp = strtok.nextToken();
            if(temp.equals("end")==false)
            {
                temp=(temp + " " + strtok.nextToken()+ " " +strtok.nextToken()+ " ");
                listeclientstitu.add(temp);
            }
            else
            {
                end=true;
            }
        }
        end=false;
        while(end==false)
        {
            String temp = strtok.nextToken();
            if(temp.equals("end")==false)
            {
                temp=(temp + " " + strtok.nextToken()+ " " );
                listeclientsacc.add(temp);
            }
            else
            {
                end=true;
            }
        }
        for(int i=0;i<listetraversees.size();i++)
        {
            CBTraversee.addItem(listetraversees.get(i));
        }
        for(int i=0;i<listeclientstitu.size();i++)
        {
            CBClient.addItem(listeclientstitu.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelNom = new javax.swing.JLabel();
        labmatricule = new javax.swing.JLabel();
        MatriculeTitu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NbPassagerSpinner = new javax.swing.JSpinner();
        OKButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        CBTraversee = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CBClient = new javax.swing.JComboBox<>();
        newCli = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("Formulaire Voyageur Titulaire");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Achat");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACHAT TICKET");
        jLabel1.setToolTipText("");

        jLabel2.setText("Formulaire Voyageur Titulaire");

        LabelNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNom.setText("Nom");

        labmatricule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labmatricule.setText("Matricule Voiture");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre passager");

        NbPassagerSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        NbPassagerSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NbPassagerSpinnerStateChanged(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Traversée");

        newCli.setText("Nouveau client");
        newCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(annulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBClient, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MatriculeTitu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(labmatricule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NbPassagerSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(newCli)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CBTraversee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNom)
                    .addComponent(labmatricule)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculeTitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbPassagerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBTraversee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerButton)
                    .addComponent(OKButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    private void NbPassagerSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NbPassagerSpinnerStateChanged
      
    }//GEN-LAST:event_NbPassagerSpinnerStateChanged

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        Mywindow.AchatOk(this);
        this.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void newCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCliActionPerformed
        // TODO add your handling code here:
        NewClient nc = new NewClient(this); 
        nc.setVisible(true); 
    }//GEN-LAST:event_newCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy_ticket_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy_ticket_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy_ticket_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy_ticket_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy_ticket_window(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CBClient;
    public javax.swing.JComboBox<String> CBTraversee;
    private javax.swing.JLabel LabelNom;
    public javax.swing.JTextField MatriculeTitu;
    public javax.swing.JSpinner NbPassagerSpinner;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labmatricule;
    private javax.swing.JButton newCli;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTextField NomPassager1;
}
