/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rti_Windows;

import java.io.ObjectInputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
import network.Network;
import protocoles.ReponseProtocol;
import protocoles.RequeteProtocol;

/**
 *
 * @author tiboo
 */
public class CustomerWindow extends javax.swing.JFrame {

    private Socket cSock;
    private ObjectInputStream ois; 
    
    /**
     * Creates new form CustomerWindow
     */
    public CustomerWindow() {
        initComponents();
    }
    public CustomerWindow(Socket s) {
        initComponents(); 
        cSock = s; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requeteTxt = new javax.swing.JTextField();
        validerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        buyTicketButton = new javax.swing.JButton();
        verfiBookingButton = new javax.swing.JButton();
        nbrPassagerTxt = new javax.swing.JTextField();
        reservationTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Client");

        validerButton.setText("Valider");

        jLabel1.setText("Nombre de passagers :");

        jLabel2.setText("Réservation :");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buyTicketButton.setText("Buy Ticket");
        buyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketButtonActionPerformed(evt);
            }
        });

        verfiBookingButton.setText("Verif. Booking");
        verfiBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verfiBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reservationTxt)
                                    .addComponent(nbrPassagerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(verfiBookingButton)
                                .addGap(12, 12, 12)
                                .addComponent(buyTicketButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton))
                            .addComponent(requeteTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(validerButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(reservationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nbrPassagerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verfiBookingButton)
                    .addComponent(buyTicketButton)
                    .addComponent(closeButton))
                .addGap(30, 30, 30)
                .addComponent(requeteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(validerButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verfiBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verfiBookingButtonActionPerformed
        // TODO add your handling code here:
        String mess = reservationTxt.getText() +"#"+ nbrPassagerTxt.getText();
        RequeteProtocol requete = new RequeteProtocol(RequeteProtocol.VERIF_BOOKING,mess);
        Network n = new Network();
        cSock = n.Init(); 
        n.SendRequest(cSock,requete);
        ReponseProtocol reponse = null;
        try {
            ois = new ObjectInputStream(cSock.getInputStream());
            reponse = (ReponseProtocol)ois.readObject(); 
            if(reponse.getCode()==ReponseProtocol.RESERV_OK) {
                JOptionPane.showMessageDialog(null, "Votre réservation est juste", "Resultat réservation", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Votre réservation est incorecte", "Resultat réservation", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e) {
            System.err.println("<CustomerWindow> " + e.getMessage()); 
        } 
    }//GEN-LAST:event_verfiBookingButtonActionPerformed

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:
        Buy_ticket_window btw=new Buy_ticket_window(this);
        btw.setVisible(true);
    }//GEN-LAST:event_buyTicketButtonActionPerformed

    public void AchatOk(Buy_ticket_window btw)
    {
        String mess = (btw.NomTitu.getText()+"#"+btw.PrenomTitu.getText()+"#"+btw.MatriculeTitu.getText()+"#");
        if(btw.NewCli.isSelected()) {
            mess+=("true"+"#"+btw.JTFemailtitu.getText()+"#"+btw.JTFadressetitu.getText()+"#"+btw.JTFpaystitu.getText()+"#");
        }
        else {
            mess+=("false"+"#"+"null"+"#"+"null"+"#"+"null"+"#");
        }
        mess+=((int)btw.NbPassagerSpinner.getValue()+"#");
        for(int i=0;i<(int)btw.NbPassagerSpinner.getValue();i++) {
            mess+=(btw.tabJTFnom.get(i).getText()+"#"+btw.tabJTFprenom.get(i).getText()+"#");
            
            if(btw.chknpassager.get(i).isSelected()) {
                 mess+=("true"+"#"+btw.tabJTFadresse.get(i).getText()+"#"+btw.tabJTFpays.get(i).getText()+"#");
            }
            else {
                mess+=("false"+"#"+"null"+"#"+"null"+"#");
            }
        }
        RequeteProtocol requete = new RequeteProtocol(RequeteProtocol.BUY_TICKET,mess);
        Network n = new Network();
        cSock = n.Init(); 
        n.SendRequest(cSock,requete);
        
        ReponseProtocol reponse = null;
        try {
            ois = new ObjectInputStream(cSock.getInputStream());
            reponse = (ReponseProtocol)ois.readObject();
            
            if(reponse.getCode()==ReponseProtocol.ACHAT_OK) {
                JOptionPane.showMessageDialog(null, "Votre achat est bon", "Resultat achat", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Votre achat est incorrect", "Resultat achat", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e) {
            System.err.println("<AchatOk> " + e.getMessage());
        } 
    }
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nbrPassagerTxt;
    private javax.swing.JTextField requeteTxt;
    private javax.swing.JTextField reservationTxt;
    private javax.swing.JButton validerButton;
    private javax.swing.JButton verfiBookingButton;
    // End of variables declaration//GEN-END:variables
}
