/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rti_Windows;

import CHECKINAP.RequeteProtocol;
import CHECKINAP.ReponseProtocol;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import network.Network;

/**
 *
 * @author Pierre
 */
public class LoginWindow extends javax.swing.JFrame {

    private ObjectInputStream ois;
    private Socket cSock; 
    private CustomerWindow custWindow; 
    
    private static Properties hashtable = new Properties();
    public Properties getHashtable(){return hashtable;}
    
    public void setCustWindow(CustomerWindow cw) {custWindow = cw;} 
    public CustomerWindow getCustWindow() {return custWindow;} 
    
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        
        try {
            FileInputStream in = new FileInputStream("config.properties");
            getHashtable().load(in);
        } catch (FileNotFoundException ex) {
            getHashtable().put("admin", "admin"); 
        }
        catch(IOException e) {
            System.err.println("<LoginWindow> Erreur properties : " + e.getMessage()); 
        }
    }
    public LoginWindow(CustomerWindow c)
    {
        setCustWindow(c);
        initComponents();
        try {
            FileInputStream in = new FileInputStream("config.properties");
            getHashtable().load(in);
        } catch (FileNotFoundException ex) {
            getHashtable().put("admin", "admin"); 
        }
        catch(IOException e) {
            System.err.println("<LoginWindow> Erreur properties : " + e.getMessage()); 
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        validerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        pwdTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        loginTxt.setText("admin");
        loginTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginTxtKeyPressed(evt);
            }
        });

        jLabel1.setText("Login :");

        jLabel2.setText("Password :");

        validerButton.setText("Valider");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        pwdTxt.setText("admin");
        pwdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdTxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pwdTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(validerButton)
                        .addGap(47, 47, 47)
                        .addComponent(annulerButton)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validerButton)
                    .addComponent(annulerButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
        // TODO add your handling code here:
        RequeteProtocol req = new RequeteProtocol(RequeteProtocol.LOGIN, loginTxt.getText().concat("#" + String.valueOf(pwdTxt.getPassword())));
        
        Network n = new Network();
        cSock = n.Init(); 
        n.SendRequest(cSock, req); 
        
        ReponseProtocol rep = null;
        try {
            ois = new ObjectInputStream(cSock.getInputStream()); 
            rep = (ReponseProtocol)ois.readObject(); // va pas 
            System.out.println("<LoginWindow> *** Reponse reçue");
            
            if(rep.getCode() == ReponseProtocol.LOGIN_OK) {
                CustomerWindow cw = new CustomerWindow(); 
                cw.setVisible(true); 
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Connexion incorrecte !", "Petit filou !", JOptionPane.ERROR_MESSAGE); 
            }
        }
        catch (Exception e) { 
            System.err.println("<LoginWindow> " + e.getMessage()); 
            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_validerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void loginTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            validerButtonActionPerformed(null); 
    }//GEN-LAST:event_loginTxtKeyPressed

    private void pwdTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            validerButtonActionPerformed(null); 
    }//GEN-LAST:event_pwdTxtKeyPressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
